@AgroSolutions_Ingestao_WebApi_HostAddress = http://localhost:5000

### Health
GET {{AgroSolutions_Ingestao_WebApi_HostAddress}}/health/live

### Ingestão - criar leitura
POST {{AgroSolutions_Ingestao_WebApi_HostAddress}}/api/v1/leituras-sensores
Content-Type: application/json

{
  "idPropriedade": "00000000-0000-0000-0000-000000000001",
  "idTalhao": "00000000-0000-0000-0000-000000000001",
  "origem": "simulador",
  "dataHoraCapturaUtc": "2026-01-25T12:00:00Z",
  "metricas": {
    "umidadeSoloPercentual": 42.7,
    "temperaturaCelsius": 28.1,
    "precipitacaoMilimetros": 3.2
  },
  "meta": {
    "idDispositivo": "SIM-001",
    "correlationId": "demo-123"
  }
}

### Ingestão - consultar
GET {{AgroSolutions_Ingestao_WebApi_HostAddress}}/api/v1/leituras-sensores?idTalhao=00000000-0000-0000-0000-000000000001&deUtc=2026-01-25T00:00:00Z&ateUtc=2026-01-26T00:00:00Z&agruparMinutos=5
