apiVersion: 1
datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://kps-kube-prometheus-stack-prometheus.agrosolutions-observability:9090
  isDefault: true
- name: SQLServer
  type: mssql
  uid: mssql-analise
  url: agrosolutions.database.windows.net
  user: usr_agro
  secureJsonData:
    password: Fi@p2026
  jsonData:
    database: Analise
    encrypt: "true"
    tlsSkipVerify: true
- name: Jaeger
  type: jaeger
  uid: jaeger
  access: proxy
  url: http://jaeger-collector:16686
- name: Loki
  type: loki
  access: proxy
  url: http://loki:3100
  jsonData:
    derivedFields:
      - datasourceUid: jaeger
        matcherRegex: '(?:TraceId|@tr)":"(\w+)"'
        name: TraceID
        url: $${__value.raw}
